FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY LongPollingWorker/*.csproj ./LongPollingWorker/
COPY DomainLogic/*.csproj ./DomainLogic/
COPY WebHookApp/*.csproj ./WebHookApp/
RUN dotnet restore

# copy everything else and build app
COPY LongPollingWorker/. ./LongPollingWorker/
COPY DomainLogic/. ./DomainLogic/
COPY WebHookApp/. ./WebHookApp/

WORKDIR /app/WebHookApp
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/WebHookApp/out ./

ENTRYPOINT ["dotnet", "WebHookApp.dll"]